### ISSUE TITLE
`--junitxml` creates an empty report

### ISSUE THREAD

**Issue by kevlened** [browsertron/pytest-parallel#24]

**Comment by SizovIgor** [comment]
so, which the status for this issue?

**Comment by svetlyak40wt** [comment]
Hey, @kevlened!

I was able to figure out what is the cause of this issue and to fix it!

Here is a pull:

https://github.com/browsertron/pytest-parallel/pull/68

**Comment by svetlyak40wt** [comment]
@SizovIgor please, test my  fix in the https://github.com/browsertron/pytest-parallel/pull/68

**Comment by kevlened** [comment]
I've merged the changes from @svetlyak40wt , so this should be resolved in [`0.1.0`](https://pypi.org/project/pytest-parallel/0.1.0/)
