### ISSUE TITLE
 AttributeError: 'ThreadLocalEnviron' object has no attribute 'copy'

### ISSUE THREAD

**Issue by sar772004** [browsertron/pytest-parallel#6]
I was using delegator package and had this error, We probably need a copy function in ThreadLocalEnviron class, like this
    def copy(self):
        return dict(self)

ERROR:
    c = delegator.run('ip netns')
../build/debug/test/pyshl-infra/venv/lib64/python3.6/site-packages/delegator.py:280: in run
    c.run(block=block, binary=binary, cwd=cwd, env=env)
../build/debug/test/pyshl-infra/venv/lib64/python3.6/site-packages/delegator.py:146: in run
    popen_kwargs = self._default_popen_kwargs.copy()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Command 'ip netns'>

    @property
    def _default_popen_kwargs(self):
        return {
>           'env': os.environ.copy(),
            'stdin': subprocess.PIPE,
            'stdout': subprocess.PIPE,
            'stderr': subprocess.PIPE,
            'shell': True,
            'universal_newlines': True,
            'bufsize': 0
        }
E       AttributeError: 'ThreadLocalEnviron' object has no attribute 'copy'

../build/debug/test/pyshl-infra/venv/lib64/python3.6/site-packages/delegator.py:40: AttributeError

**Comment by kevlened** [comment]
Hi @sar772004, thanks for letting me know!

I shim `os.environ` to ensure some py.test-specific keys can be accessed in a thread safe way. That shim, `ThreadLocalEnviron`, was missing a lot of the methods from the actual `os.environ`. I've added those methods, so you should be able to use them in `0.0.3`, which is on PyPI now.

**Comment by sar772004** [comment]
Thanks @kevlened for the quick fix.. appreciate it.
