### ISSUE TITLE
Using pytest parallel with markers gives AttributeError: Can't pickle local object 'ArgumentParser.__init__.<locals>.identity'

### ISSUE THREAD

**Issue by GowriShankariSurendran** [browsertron/pytest-parallel#9]
When we use pytest parallel and run tests per test suite, it works like a charm.
But when we use it to send test cases which has be attributed with "markers" then we get an "Attribute Error"

py.test -sv --workers 2 -m ewlc com/tests/mock/e2e/ -k test --config device_mock_Cluster.yaml 
===================================================================================================== test session starts =====================================================================================================
platform darwin -- Python 3.6.5, pytest-3.8.0, py-1.5.4, pluggy-0.7.1 -- /Users/gosurend/.virtualenvs/checkuniq/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.6.5', 'Platform': 'Darwin-16.7.0-x86_64-i386-64bit', 'Packages': {'pytest': '3.8.0', 'py': '1.5.4', 'pluggy': '0.7.1'}, 'Plugins': {'xdist': '1.23.0', 'parallel': '0.0.2', 'ordering': '0.5', 'mock': '0.10.1', 'metadata': '1.7.0', 'html': '1.14.2', 'forked': '0.2', 'dependency': '0.3.2', 'cov': '2.2.1', 'assume': '1.2', 'flaky': '3.3.0'}, 'ASSURANCE_VERSION': None}
rootdir: /Users/gosurend/Documents/Wireless/QA_Always_latest/qa-assurance-common/assurance_it, inifile: pytest.ini
plugins: xdist-1.23.0, parallel-0.0.2, ordering-0.5, mock-0.10.1, metadata-1.7.0, html-1.14.2, forked-0.2, dependency-0.3.2, cov-2.2.1, assume-1.2, flaky-3.3.0
collecting 594 items / 2 errors                                                                                                                                                                                               INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/_pytest/main.py", line 178, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/_pytest/main.py", line 214, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/_pytest/main.py", line 224, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/_pytest/main.py", line 432, in perform_collect
INTERNALERROR>     session=self, config=self.config, items=items
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/_pytest/mark/__init__.py", line 156, in pytest_collection_modifyitems
INTERNALERROR>     deselect_by_mark(items, config)
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/_pytest/mark/__init__.py", line 150, in deselect_by_mark
INTERNALERROR>     config.hook.pytest_deselected(items=deselected)
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/gosurend/.virtualenvs/checkuniq/lib/python3.6/site-packages/_pytest/terminal.py", line 363, in pytest_deselected
INTERNALERROR>     self.stats.setdefault("deselected", []).extend(items)
INTERNALERROR>   File "<string>", line 2, in extend
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/managers.py", line 756, in _callmethod
INTERNALERROR>     conn.send((self._id, methodname, args, kwds))
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/connection.py", line 206, in send
INTERNALERROR>     self._send_bytes(_ForkingPickler.dumps(obj))
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
INTERNALERROR>     cls(buf, protocol).dump(obj)
INTERNALERROR> AttributeError: Can't pickle local object 'ArgumentParser.__init__.<locals>.identity'

Any fixes to this problem will be much appreciated!

**Comment by kevlened** [comment]
Interesting. I'll take a look

**Comment by kevlened** [comment]
I'm having trouble reproducing the issue. What types of markers are you using? Are these custom markers or the built-in markers (`skip`, `skipif`, `xfail`, `parameterize`)?

**Comment by GowriShankariSurendran** [comment]
Awesome! Let me test this right away and update!!

**Comment by GowriShankariSurendran** [comment]
@kevlened - Works perfectly and it is thread safe again which is why I preferred this over xdist!! Thanks for such a prompt response!!
